/**
 * Achievement System Types
 * 
 * Defines all achievement-related types, categories, and structures
 */

export type AchievementCategory = 
  | 'first_steps'    // Erste Schritte
  | 'scoring'        // Score-bezogen
  | 'checkout'       // Checkout-bezogen
  | 'training'       // Training-bezogen
  | 'consistency'    // Beständigkeit
  | 'special'        // Spezielle Achievements
  | 'master';        // Meisterschaft

export type AchievementTier = 'bronze' | 'silver' | 'gold' | 'platinum' | 'diamond';

export interface Achievement {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  tier: AchievementTier;
  icon: string;
  points: number;
  requirement: {
    type: 'count' | 'value' | 'streak' | 'special';
    target: number;
    metric: string;
  };
  hidden?: boolean; // Hidden until unlocked
  rarity?: 'common' | 'rare' | 'epic' | 'legendary';
}

export interface UnlockedAchievement {
  achievementId: string;
  unlockedAt: Date;
  playerId: string;
  gameId?: string; // Optional: ID des Spiels, in dem es freigeschaltet wurde
}

export interface PlayerAchievementProgress {
  playerId: string;
  unlockedAchievements: UnlockedAchievement[];
  progress: {
    [achievementId: string]: {
      current: number;
      target: number;
      percentage: number;
    };
  };
  totalPoints: number;
  lastUnlocked?: UnlockedAchievement;
}

export interface AchievementNotification {
  achievement: Achievement;
  playerId: string;
  timestamp: Date;
}

// All available achievements in the game
export const ACHIEVEMENTS: Achievement[] = [
  // ===== FIRST STEPS (5 Achievements) =====
  {
    id: 'first_game',
    name: 'Erste Schritte',
    description: 'Beende dein erstes Spiel',
    category: 'first_steps',
    tier: 'bronze',
    icon: '🎯',
    points: 10,
    requirement: { type: 'count', target: 1, metric: 'games_played' },
    rarity: 'common',
  },
  {
    id: 'rookie',
    name: 'Rookie',
    description: 'Spiele 10 Spiele',
    category: 'first_steps',
    tier: 'bronze',
    icon: '🎮',
    points: 25,
    requirement: { type: 'count', target: 10, metric: 'games_played' },
    rarity: 'common',
  },
  {
    id: 'veteran',
    name: 'Veteran',
    description: 'Spiele 50 Spiele',
    category: 'first_steps',
    tier: 'silver',
    icon: '⭐',
    points: 50,
    requirement: { type: 'count', target: 50, metric: 'games_played' },
    rarity: 'rare',
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: 'Spiele 100 Spiele',
    category: 'first_steps',
    tier: 'gold',
    icon: '💯',
    points: 100,
    requirement: { type: 'count', target: 100, metric: 'games_played' },
    rarity: 'epic',
  },
  {
    id: 'legend',
    name: 'Legende',
    description: 'Spiele 500 Spiele',
    category: 'first_steps',
    tier: 'platinum',
    icon: '👑',
    points: 250,
    requirement: { type: 'count', target: 500, metric: 'games_played' },
    rarity: 'legendary',
  },

  // ===== SCORING (5 Achievements) =====
  {
    id: 'ton_80',
    name: 'Ton 80',
    description: 'Erziele deinen ersten 180',
    category: 'scoring',
    tier: 'silver',
    icon: '🔥',
    points: 50,
    requirement: { type: 'count', target: 1, metric: 'score_180' },
    rarity: 'rare',
  },
  {
    id: 'max_out',
    name: 'Max Out',
    description: 'Erziele 10x einen 180',
    category: 'scoring',
    tier: 'gold',
    icon: '💥',
    points: 100,
    requirement: { type: 'count', target: 10, metric: 'score_180' },
    rarity: 'epic',
  },
  {
    id: 'high_roller',
    name: 'High Roller',
    description: 'Erreiche einen Average von 60 in einem Spiel',
    category: 'scoring',
    tier: 'silver',
    icon: '📈',
    points: 50,
    requirement: { type: 'value', target: 60, metric: 'match_average' },
    rarity: 'rare',
  },
  {
    id: 'pro_scorer',
    name: 'Pro Scorer',
    description: 'Erreiche einen Average von 80 in einem Spiel',
    category: 'scoring',
    tier: 'gold',
    icon: '🎖️',
    points: 100,
    requirement: { type: 'value', target: 80, metric: 'match_average' },
    rarity: 'epic',
  },
  {
    id: 'world_class',
    name: 'Weltklasse',
    description: 'Erreiche einen Average von 100 in einem Spiel',
    category: 'scoring',
    tier: 'diamond',
    icon: '💎',
    points: 250,
    requirement: { type: 'value', target: 100, metric: 'match_average' },
    rarity: 'legendary',
  },

  // ===== CHECKOUT (4 Achievements) =====
  {
    id: 'checkout_king',
    name: 'Checkout King',
    description: 'Erreiche eine Checkout-Quote von 50% (min. 10 Versuche)',
    category: 'checkout',
    tier: 'gold',
    icon: '🎯',
    points: 75,
    requirement: { type: 'value', target: 50, metric: 'checkout_percentage' },
    rarity: 'epic',
  },
  {
    id: 'big_fish',
    name: 'Big Fish',
    description: 'Checke 170 aus',
    category: 'checkout',
    tier: 'gold',
    icon: '🐟',
    points: 100,
    requirement: { type: 'special', target: 170, metric: 'checkout_value' },
    rarity: 'epic',
    hidden: true,
  },
  {
    id: 'bullseye_master',
    name: 'Bullseye Master',
    description: 'Checke mit Double Bull aus',
    category: 'checkout',
    tier: 'silver',
    icon: '🎯',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'checkout_bullseye' },
    rarity: 'rare',
  },
  {
    id: 'perfect_finish',
    name: 'Perfect Finish',
    description: 'Checke einen exakten Score ohne Bust',
    category: 'checkout',
    tier: 'bronze',
    icon: '✨',
    points: 25,
    requirement: { type: 'count', target: 1, metric: 'perfect_checkout' },
    rarity: 'common',
  },

  // ===== TRAINING (3 Achievements) =====
  {
    id: 'trainee',
    name: 'Trainee',
    description: 'Absolviere dein erstes Training',
    category: 'training',
    tier: 'bronze',
    icon: '🎓',
    points: 25,
    requirement: { type: 'count', target: 1, metric: 'training_completed' },
    rarity: 'common',
  },
  {
    id: 'dedicated',
    name: 'Dedicated',
    description: 'Absolviere 50 Trainingseinheiten',
    category: 'training',
    tier: 'silver',
    icon: '💪',
    points: 75,
    requirement: { type: 'count', target: 50, metric: 'training_completed' },
    rarity: 'rare',
  },
  {
    id: 'master_trainer',
    name: 'Master Trainer',
    description: 'Absolviere alle 6 Trainingsmodi',
    category: 'training',
    tier: 'gold',
    icon: '🏆',
    points: 100,
    requirement: { type: 'special', target: 6, metric: 'training_all_modes' },
    rarity: 'epic',
  },

  // ===== CONSISTENCY (2 Achievements) =====
  {
    id: 'winning_streak',
    name: 'Siegesserie',
    description: 'Gewinne 5 Spiele in Folge',
    category: 'consistency',
    tier: 'gold',
    icon: '🔥',
    points: 100,
    requirement: { type: 'streak', target: 5, metric: 'wins' },
    rarity: 'epic',
  },
  {
    id: 'no_bust',
    name: 'No Bust',
    description: 'Gewinne ein Leg ohne einzigen Bust',
    category: 'consistency',
    tier: 'silver',
    icon: '✅',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'leg_no_bust' },
    rarity: 'rare',
  },

  // ===== SPECIAL & MASTER (1 Achievement) =====
  {
    id: 'nine_darter',
    name: '9-Darter',
    description: 'Beende ein Leg mit nur 9 Darts (501)',
    category: 'special',
    tier: 'diamond',
    icon: '💫',
    points: 500,
    requirement: { type: 'special', target: 9, metric: 'leg_darts' },
    rarity: 'legendary',
    hidden: true,
  },

  // ===== ADDITIONAL SCORING ACHIEVEMENTS (7) =====
  {
    id: 'ton_plus',
    name: 'Ton Plus',
    description: 'Erziele einen Score von 100+',
    category: 'scoring',
    tier: 'bronze',
    icon: '💯',
    points: 25,
    requirement: { type: 'count', target: 1, metric: 'score_100_plus' },
    rarity: 'common',
  },
  {
    id: 'century_club',
    name: 'Century Club',
    description: 'Erziele 100x einen Score von 100+',
    category: 'scoring',
    tier: 'gold',
    icon: '🎪',
    points: 100,
    requirement: { type: 'count', target: 100, metric: 'score_100_plus' },
    rarity: 'epic',
  },
  {
    id: 'consistent_scorer',
    name: 'Konstanter Scorer',
    description: 'Erziele 10 Würfe hintereinander mit 60+',
    category: 'scoring',
    tier: 'silver',
    icon: '🎯',
    points: 75,
    requirement: { type: 'streak', target: 10, metric: 'score_60_plus' },
    rarity: 'rare',
  },
  {
    id: 'triple_master',
    name: 'Triple Meister',
    description: 'Treffe 100 Triple-Felder',
    category: 'scoring',
    tier: 'silver',
    icon: '🎯',
    points: 50,
    requirement: { type: 'count', target: 100, metric: 'triples_hit' },
    rarity: 'rare',
  },
  {
    id: 'perfect_round',
    name: 'Perfekte Runde',
    description: 'Erziele 3x Triple-20 in einem Visit (180)',
    category: 'scoring',
    tier: 'gold',
    icon: '⭐',
    points: 75,
    requirement: { type: 'special', target: 1, metric: 'perfect_180' },
    rarity: 'epic',
  },
  {
    id: 'Shanghai',
    name: 'Shanghai',
    description: 'Treffe Single, Double und Triple der gleichen Zahl',
    category: 'scoring',
    tier: 'silver',
    icon: '🏯',
    points: 60,
    requirement: { type: 'special', target: 1, metric: 'shanghai' },
    rarity: 'rare',
    hidden: true,
  },
  {
    id: 'low_ton',
    name: 'Low Ton',
    description: 'Erziele exakt 100 Punkte',
    category: 'scoring',
    tier: 'bronze',
    icon: '🎲',
    points: 20,
    requirement: { type: 'special', target: 100, metric: 'exact_score' },
    rarity: 'common',
  },

  // ===== ADDITIONAL CHECKOUT ACHIEVEMENTS (8) =====
  {
    id: 'checkout_novice',
    name: 'Checkout Anfänger',
    description: 'Checke dein erstes Spiel aus',
    category: 'checkout',
    tier: 'bronze',
    icon: '🎯',
    points: 10,
    requirement: { type: 'count', target: 1, metric: 'checkouts' },
    rarity: 'common',
  },
  {
    id: 'madhouse',
    name: 'Madhouse',
    description: 'Checke mit Double 1 aus',
    category: 'checkout',
    tier: 'silver',
    icon: '🏠',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'checkout_d1' },
    rarity: 'rare',
    hidden: true,
  },
  {
    id: 'century_checkout',
    name: 'Century Checkout',
    description: 'Checke 100 oder mehr aus',
    category: 'checkout',
    tier: 'gold',
    icon: '💯',
    points: 75,
    requirement: { type: 'special', target: 100, metric: 'checkout_value_min' },
    rarity: 'epic',
  },
  {
    id: 'double_trouble',
    name: 'Double Trouble',
    description: 'Checke 10 verschiedene Double-Felder',
    category: 'checkout',
    tier: 'silver',
    icon: '🎯',
    points: 60,
    requirement: { type: 'count', target: 10, metric: 'unique_doubles' },
    rarity: 'rare',
  },
  {
    id: 'favorite_double',
    name: 'Lieblings-Double',
    description: 'Checke 25x mit dem gleichen Double aus',
    category: 'checkout',
    tier: 'gold',
    icon: '❤️',
    points: 75,
    requirement: { type: 'count', target: 25, metric: 'same_double' },
    rarity: 'epic',
  },
  {
    id: 'quick_finish',
    name: 'Schneller Abschluss',
    description: 'Checke in unter 12 Darts (301)',
    category: 'checkout',
    tier: 'silver',
    icon: '⚡',
    points: 50,
    requirement: { type: 'special', target: 12, metric: 'checkout_darts_max' },
    rarity: 'rare',
  },
  {
    id: 'checkout_master',
    name: 'Checkout Meister',
    description: 'Erreiche 100 erfolgreiche Checkouts',
    category: 'checkout',
    tier: 'platinum',
    icon: '👑',
    points: 150,
    requirement: { type: 'count', target: 100, metric: 'checkouts' },
    rarity: 'legendary',
  },
  {
    id: 'big_40',
    name: 'Big 40',
    description: 'Checke genau 40 aus (D20)',
    category: 'checkout',
    tier: 'bronze',
    icon: '🎯',
    points: 25,
    requirement: { type: 'special', target: 40, metric: 'checkout_value' },
    rarity: 'common',
  },

  // ===== ADDITIONAL CONSISTENCY ACHIEVEMENTS (6) =====
  {
    id: 'comeback_king',
    name: 'Comeback King',
    description: 'Gewinne ein Spiel nach 0:2 Rückstand',
    category: 'consistency',
    tier: 'gold',
    icon: '👑',
    points: 100,
    requirement: { type: 'special', target: 1, metric: 'comeback_win' },
    rarity: 'epic',
  },
  {
    id: 'unstoppable',
    name: 'Unaufhaltsam',
    description: 'Gewinne 10 Spiele in Folge',
    category: 'consistency',
    tier: 'platinum',
    icon: '🔥',
    points: 200,
    requirement: { type: 'streak', target: 10, metric: 'wins' },
    rarity: 'legendary',
  },
  {
    id: 'perfect_leg',
    name: 'Perfektes Leg',
    description: 'Gewinne ein Leg mit über 100 Average',
    category: 'consistency',
    tier: 'platinum',
    icon: '💎',
    points: 150,
    requirement: { type: 'special', target: 100, metric: 'leg_average' },
    rarity: 'legendary',
  },
  {
    id: 'clutch_player',
    name: 'Clutch Player',
    description: 'Gewinne 5 Spiele im Decider',
    category: 'consistency',
    tier: 'gold',
    icon: '🎪',
    points: 100,
    requirement: { type: 'count', target: 5, metric: 'decider_wins' },
    rarity: 'epic',
  },
  {
    id: 'never_give_up',
    name: 'Never Give Up',
    description: 'Hole einen Rückstand von 200+ Punkten auf',
    category: 'consistency',
    tier: 'silver',
    icon: '💪',
    points: 75,
    requirement: { type: 'special', target: 200, metric: 'comeback_points' },
    rarity: 'rare',
  },
  {
    id: 'clean_sweep',
    name: 'Clean Sweep',
    description: 'Gewinne ein Match ohne Satzverlust (Best of 5)',
    category: 'consistency',
    tier: 'gold',
    icon: '🧹',
    points: 75,
    requirement: { type: 'special', target: 1, metric: 'whitewash' },
    rarity: 'epic',
  },

  // ===== ADDITIONAL TRAINING ACHIEVEMENTS (4) =====
  {
    id: 'training_addict',
    name: 'Training Junkie',
    description: 'Absolviere 100 Trainingseinheiten',
    category: 'training',
    tier: 'gold',
    icon: '🏋️',
    points: 100,
    requirement: { type: 'count', target: 100, metric: 'training_completed' },
    rarity: 'epic',
  },
  {
    id: 'around_the_clock',
    name: 'Around the Clock',
    description: 'Treffe alle Zahlen von 1-20 in einem Training',
    category: 'training',
    tier: 'silver',
    icon: '🕐',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'training_all_numbers' },
    rarity: 'rare',
  },
  {
    id: 'training_perfectionist',
    name: 'Training Perfektionist',
    description: 'Erreiche 100% in einem Training',
    category: 'training',
    tier: 'gold',
    icon: '✨',
    points: 75,
    requirement: { type: 'special', target: 100, metric: 'training_perfect' },
    rarity: 'epic',
  },
  {
    id: 'early_bird',
    name: 'Frühaufsteher',
    description: 'Absolviere ein Training vor 8 Uhr morgens',
    category: 'training',
    tier: 'bronze',
    icon: '🌅',
    points: 25,
    requirement: { type: 'special', target: 1, metric: 'training_early' },
    rarity: 'common',
    hidden: true,
  },

  // ===== ADDITIONAL SPECIAL & MASTER ACHIEVEMENTS (5) =====
  {
    id: 'hat_trick',
    name: 'Hat Trick',
    description: 'Erziele 3x 180 in einem Spiel',
    category: 'special',
    tier: 'platinum',
    icon: '🎩',
    points: 200,
    requirement: { type: 'special', target: 3, metric: 'match_180_count' },
    rarity: 'legendary',
    hidden: true,
  },
  {
    id: 'twelve_darter',
    name: '12-Darter',
    description: 'Beende ein Leg mit nur 12 Darts (501)',
    category: 'special',
    tier: 'platinum',
    icon: '🌟',
    points: 300,
    requirement: { type: 'special', target: 12, metric: 'leg_darts' },
    rarity: 'legendary',
    hidden: true,
  },
  {
    id: 'grand_master',
    name: 'Großmeister',
    description: 'Erreiche 10.000 Achievement-Punkte',
    category: 'master',
    tier: 'diamond',
    icon: '👑',
    points: 500,
    requirement: { type: 'value', target: 10000, metric: 'achievement_points' },
    rarity: 'legendary',
  },
  {
    id: 'all_rounder',
    name: 'Allrounder',
    description: 'Gewinne je 10 Spiele in 301, 501 und 701',
    category: 'master',
    tier: 'platinum',
    icon: '🎯',
    points: 150,
    requirement: { type: 'special', target: 10, metric: 'wins_all_modes' },
    rarity: 'legendary',
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    description: 'Beende ein Spiel in unter 5 Minuten',
    category: 'special',
    tier: 'gold',
    icon: '⚡',
    points: 75,
    requirement: { type: 'special', target: 300, metric: 'game_time_max' },
    rarity: 'epic',
    hidden: true,
  },

  // ===== ADDITIONAL FIRST STEPS ACHIEVEMENTS (10) =====
  {
    id: 'first_win',
    name: 'Erster Sieg',
    description: 'Gewinne dein erstes Spiel',
    category: 'first_steps',
    tier: 'bronze',
    icon: '🏆',
    points: 15,
    requirement: { type: 'count', target: 1, metric: 'wins' },
    rarity: 'common',
  },
  {
    id: 'champion',
    name: 'Champion',
    description: 'Gewinne 25 Spiele',
    category: 'first_steps',
    tier: 'silver',
    icon: '🥇',
    points: 75,
    requirement: { type: 'count', target: 25, metric: 'wins' },
    rarity: 'rare',
  },
  {
    id: 'master_champion',
    name: 'Meister Champion',
    description: 'Gewinne 100 Spiele',
    category: 'first_steps',
    tier: 'gold',
    icon: '👑',
    points: 150,
    requirement: { type: 'count', target: 100, metric: 'wins' },
    rarity: 'epic',
  },
  {
    id: 'ultimate_champion',
    name: 'Ultimativer Champion',
    description: 'Gewinne 250 Spiele',
    category: 'first_steps',
    tier: 'platinum',
    icon: '🏅',
    points: 300,
    requirement: { type: 'count', target: 250, metric: 'wins' },
    rarity: 'legendary',
  },
  {
    id: 'millennium',
    name: 'Millennium',
    description: 'Spiele 1000 Spiele',
    category: 'first_steps',
    tier: 'diamond',
    icon: '💎',
    points: 500,
    requirement: { type: 'count', target: 1000, metric: 'games_played' },
    rarity: 'legendary',
  },
  {
    id: 'social_player',
    name: 'Geselliger Spieler',
    description: 'Spiele gegen 10 verschiedene Gegner',
    category: 'first_steps',
    tier: 'bronze',
    icon: '👥',
    points: 30,
    requirement: { type: 'count', target: 10, metric: 'unique_opponents' },
    rarity: 'common',
  },
  {
    id: 'popular',
    name: 'Beliebt',
    description: 'Spiele gegen 50 verschiedene Gegner',
    category: 'first_steps',
    tier: 'silver',
    icon: '🎭',
    points: 75,
    requirement: { type: 'count', target: 50, metric: 'unique_opponents' },
    rarity: 'rare',
  },
  {
    id: 'night_owl',
    name: 'Nachteule',
    description: 'Spiele ein Match nach Mitternacht',
    category: 'first_steps',
    tier: 'bronze',
    icon: '🦉',
    points: 20,
    requirement: { type: 'special', target: 1, metric: 'game_midnight' },
    rarity: 'common',
  },
  {
    id: 'weekend_warrior',
    name: 'Wochenend-Krieger',
    description: 'Spiele 25 Spiele am Wochenende',
    category: 'first_steps',
    tier: 'silver',
    icon: '🎉',
    points: 50,
    requirement: { type: 'count', target: 25, metric: 'weekend_games' },
    rarity: 'rare',
  },
  {
    id: 'daily_grind',
    name: 'Täglicher Einsatz',
    description: 'Spiele 7 Tage in Folge',
    category: 'first_steps',
    tier: 'gold',
    icon: '📅',
    points: 100,
    requirement: { type: 'streak', target: 7, metric: 'daily_play' },
    rarity: 'epic',
  },

  // ===== ADDITIONAL SCORING ACHIEVEMENTS (20) =====
  {
    id: 'ton_40',
    name: 'Ton 40',
    description: 'Erziele einen Score von 140',
    category: 'scoring',
    tier: 'silver',
    icon: '💥',
    points: 40,
    requirement: { type: 'special', target: 140, metric: 'exact_score' },
    rarity: 'rare',
  },
  {
    id: 'triple_twenty',
    name: 'Triple 20 Profi',
    description: 'Treffe 500x Triple-20',
    category: 'scoring',
    tier: 'gold',
    icon: '🎯',
    points: 100,
    requirement: { type: 'count', target: 500, metric: 'triple_20_hit' },
    rarity: 'epic',
  },
  {
    id: 'triple_nineteen',
    name: 'Triple 19 Spezialist',
    description: 'Treffe 250x Triple-19',
    category: 'scoring',
    tier: 'silver',
    icon: '🎯',
    points: 60,
    requirement: { type: 'count', target: 250, metric: 'triple_19_hit' },
    rarity: 'rare',
  },
  {
    id: 'triple_collector',
    name: 'Triple Sammler',
    description: 'Treffe jedes Triple-Feld mindestens einmal',
    category: 'scoring',
    tier: 'gold',
    icon: '🎪',
    points: 75,
    requirement: { type: 'special', target: 20, metric: 'all_triples' },
    rarity: 'epic',
  },
  {
    id: 'high_ton',
    name: 'High Ton',
    description: 'Erziele einen Score von 150+',
    category: 'scoring',
    tier: 'silver',
    icon: '🔥',
    points: 50,
    requirement: { type: 'count', target: 1, metric: 'score_150_plus' },
    rarity: 'rare',
  },
  {
    id: 'super_scorer',
    name: 'Super Scorer',
    description: 'Erziele 50x einen Score von 150+',
    category: 'scoring',
    tier: 'platinum',
    icon: '💫',
    points: 150,
    requirement: { type: 'count', target: 50, metric: 'score_150_plus' },
    rarity: 'legendary',
  },
  {
    id: 'bullseye_hunter',
    name: 'Bullseye Jäger',
    description: 'Treffe 50x das Bullseye',
    category: 'scoring',
    tier: 'silver',
    icon: '🎯',
    points: 50,
    requirement: { type: 'count', target: 50, metric: 'bullseye_hit' },
    rarity: 'rare',
  },
  {
    id: 'bullseye_legend',
    name: 'Bullseye Legende',
    description: 'Treffe 200x das Bullseye',
    category: 'scoring',
    tier: 'platinum',
    icon: '🎯',
    points: 150,
    requirement: { type: 'count', target: 200, metric: 'bullseye_hit' },
    rarity: 'legendary',
  },
  {
    id: 'bed_and_breakfast',
    name: 'Bed & Breakfast',
    description: 'Erziele 26 Punkte (5, 20, 1)',
    category: 'scoring',
    tier: 'bronze',
    icon: '🛏️',
    points: 15,
    requirement: { type: 'special', target: 26, metric: 'exact_score' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'double_master',
    name: 'Double Meister',
    description: 'Treffe 200 Double-Felder',
    category: 'scoring',
    tier: 'gold',
    icon: '🎯',
    points: 75,
    requirement: { type: 'count', target: 200, metric: 'doubles_hit' },
    rarity: 'epic',
  },
  {
    id: 'single_precision',
    name: 'Single Präzision',
    description: 'Treffe 1000 Single-Felder',
    category: 'scoring',
    tier: 'silver',
    icon: '🎲',
    points: 50,
    requirement: { type: 'count', target: 1000, metric: 'singles_hit' },
    rarity: 'rare',
  },
  {
    id: 'average_joe',
    name: 'Average Joe',
    description: 'Erreiche einen Average von 45 in einem Spiel',
    category: 'scoring',
    tier: 'bronze',
    icon: '📊',
    points: 25,
    requirement: { type: 'value', target: 45, metric: 'match_average' },
    rarity: 'common',
  },
  {
    id: 'consistent_average',
    name: 'Konstanter Average',
    description: 'Erreiche in 10 Spielen hintereinander 50+ Average',
    category: 'scoring',
    tier: 'gold',
    icon: '📈',
    points: 100,
    requirement: { type: 'streak', target: 10, metric: 'average_50_plus' },
    rarity: 'epic',
  },
  {
    id: 'elite_scorer',
    name: 'Elite Scorer',
    description: 'Erreiche einen Average von 90 in einem Spiel',
    category: 'scoring',
    tier: 'platinum',
    icon: '⭐',
    points: 150,
    requirement: { type: 'value', target: 90, metric: 'match_average' },
    rarity: 'legendary',
  },
  {
    id: 'ton_machine',
    name: 'Ton Maschine',
    description: 'Erziele 50x einen 180',
    category: 'scoring',
    tier: 'platinum',
    icon: '🤖',
    points: 200,
    requirement: { type: 'count', target: 50, metric: 'score_180' },
    rarity: 'legendary',
  },
  {
    id: 'triple_triple',
    name: 'Triple Triple',
    description: 'Treffe 3 Triples in einem Visit (nicht 180)',
    category: 'scoring',
    tier: 'silver',
    icon: '🎯',
    points: 40,
    requirement: { type: 'special', target: 1, metric: 'three_triples' },
    rarity: 'rare',
  },
  {
    id: 'perfect_visit',
    name: 'Perfekter Visit',
    description: 'Treffe alle 3 Darts im gleichen Segment',
    category: 'scoring',
    tier: 'bronze',
    icon: '✨',
    points: 30,
    requirement: { type: 'special', target: 1, metric: 'same_segment' },
    rarity: 'common',
  },
  {
    id: 'unlucky',
    name: 'Pechvogel',
    description: 'Treffe 3x die 1 in einem Visit',
    category: 'scoring',
    tier: 'bronze',
    icon: '😅',
    points: 10,
    requirement: { type: 'special', target: 3, metric: 'three_ones' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'lucky_seven',
    name: 'Glückliche Sieben',
    description: 'Erziele exakt 77 Punkte',
    category: 'scoring',
    tier: 'bronze',
    icon: '🍀',
    points: 20,
    requirement: { type: 'special', target: 77, metric: 'exact_score' },
    rarity: 'common',
  },
  {
    id: 'scoring_streak',
    name: 'Scoring Serie',
    description: 'Erziele 20 Würfe hintereinander mit 45+',
    category: 'scoring',
    tier: 'gold',
    icon: '🔥',
    points: 100,
    requirement: { type: 'streak', target: 20, metric: 'score_45_plus' },
    rarity: 'epic',
  },

  // ===== ADDITIONAL CHECKOUT ACHIEVEMENTS (15) =====
  {
    id: 'checkout_apprentice',
    name: 'Checkout Lehrling',
    description: 'Erreiche 10 erfolgreiche Checkouts',
    category: 'checkout',
    tier: 'bronze',
    icon: '🎓',
    points: 25,
    requirement: { type: 'count', target: 10, metric: 'checkouts' },
    rarity: 'common',
  },
  {
    id: 'checkout_expert',
    name: 'Checkout Experte',
    description: 'Erreiche 50 erfolgreiche Checkouts',
    category: 'checkout',
    tier: 'silver',
    icon: '🎯',
    points: 75,
    requirement: { type: 'count', target: 50, metric: 'checkouts' },
    rarity: 'rare',
  },
  {
    id: 'tops',
    name: 'Tops',
    description: 'Checke mit Double 20 aus',
    category: 'checkout',
    tier: 'bronze',
    icon: '🔝',
    points: 20,
    requirement: { type: 'special', target: 1, metric: 'checkout_d20' },
    rarity: 'common',
  },
  {
    id: 'favorite_tops',
    name: 'Tops Liebhaber',
    description: 'Checke 50x mit Double 20 aus',
    category: 'checkout',
    tier: 'gold',
    icon: '❤️',
    points: 100,
    requirement: { type: 'count', target: 50, metric: 'checkout_d20' },
    rarity: 'epic',
  },
  {
    id: 'double_16',
    name: 'Double 16 Spezialist',
    description: 'Checke 25x mit Double 16 aus',
    category: 'checkout',
    tier: 'silver',
    icon: '🎯',
    points: 50,
    requirement: { type: 'count', target: 25, metric: 'checkout_d16' },
    rarity: 'rare',
  },
  {
    id: 'big_checkout',
    name: 'Big Checkout',
    description: 'Checke 120 oder mehr aus',
    category: 'checkout',
    tier: 'gold',
    icon: '💪',
    points: 100,
    requirement: { type: 'special', target: 120, metric: 'checkout_value_min' },
    rarity: 'epic',
  },
  {
    id: 'massive_checkout',
    name: 'Massiver Checkout',
    description: 'Checke 150 oder mehr aus',
    category: 'checkout',
    tier: 'platinum',
    icon: '💥',
    points: 150,
    requirement: { type: 'special', target: 150, metric: 'checkout_value_min' },
    rarity: 'legendary',
  },
  {
    id: 'checkout_efficiency',
    name: 'Checkout Effizienz',
    description: 'Erreiche eine Checkout-Quote von 40% (min. 20 Versuche)',
    category: 'checkout',
    tier: 'silver',
    icon: '⚡',
    points: 50,
    requirement: { type: 'value', target: 40, metric: 'checkout_percentage' },
    rarity: 'rare',
  },
  {
    id: 'checkout_legend',
    name: 'Checkout Legende',
    description: 'Erreiche eine Checkout-Quote von 60% (min. 20 Versuche)',
    category: 'checkout',
    tier: 'platinum',
    icon: '👑',
    points: 200,
    requirement: { type: 'value', target: 60, metric: 'checkout_percentage' },
    rarity: 'legendary',
  },
  {
    id: 'one_dart_finish',
    name: 'Ein-Dart-Finish',
    description: 'Checke mit nur einem Dart aus',
    category: 'checkout',
    tier: 'bronze',
    icon: '🎯',
    points: 30,
    requirement: { type: 'special', target: 1, metric: 'checkout_one_dart' },
    rarity: 'common',
  },
  {
    id: 'two_dart_finish',
    name: 'Zwei-Dart-Finish',
    description: 'Checke mit nur zwei Darts aus',
    category: 'checkout',
    tier: 'silver',
    icon: '🎯',
    points: 40,
    requirement: { type: 'special', target: 1, metric: 'checkout_two_dart' },
    rarity: 'rare',
  },
  {
    id: 'bogey_number',
    name: 'Bogey Nummer',
    description: 'Checke 169 aus (höchste ungerade Zahl)',
    category: 'checkout',
    tier: 'platinum',
    icon: '🎱',
    points: 200,
    requirement: { type: 'special', target: 169, metric: 'checkout_value' },
    rarity: 'legendary',
    hidden: true,
  },
  {
    id: 'checkout_variety',
    name: 'Checkout Vielfalt',
    description: 'Checke mit 15 verschiedenen Werten aus',
    category: 'checkout',
    tier: 'gold',
    icon: '🌈',
    points: 75,
    requirement: { type: 'count', target: 15, metric: 'unique_checkout_values' },
    rarity: 'epic',
  },
  {
    id: 'clutch_checkout',
    name: 'Clutch Checkout',
    description: 'Checke aus wenn Gegner auf einem Checkout-Wert steht',
    category: 'checkout',
    tier: 'gold',
    icon: '⚡',
    points: 75,
    requirement: { type: 'special', target: 1, metric: 'clutch_checkout' },
    rarity: 'epic',
  },
  {
    id: 'double_bull_lover',
    name: 'Double Bull Liebhaber',
    description: 'Checke 10x mit Double Bull aus',
    category: 'checkout',
    tier: 'gold',
    icon: '🎯',
    points: 100,
    requirement: { type: 'count', target: 10, metric: 'checkout_bullseye' },
    rarity: 'epic',
  },

  // ===== ADDITIONAL CONSISTENCY ACHIEVEMENTS (15) =====
  {
    id: 'double_digit_wins',
    name: 'Zweistellig',
    description: 'Gewinne 10 Spiele',
    category: 'consistency',
    tier: 'bronze',
    icon: '🔟',
    points: 30,
    requirement: { type: 'count', target: 10, metric: 'wins' },
    rarity: 'common',
  },
  {
    id: 'fifty_wins',
    name: 'Fifty Club',
    description: 'Gewinne 50 Spiele',
    category: 'consistency',
    tier: 'silver',
    icon: '5️⃣0️⃣',
    points: 75,
    requirement: { type: 'count', target: 50, metric: 'wins' },
    rarity: 'rare',
  },
  {
    id: 'win_streak_3',
    name: 'Hattrick',
    description: 'Gewinne 3 Spiele in Folge',
    category: 'consistency',
    tier: 'bronze',
    icon: '🎩',
    points: 40,
    requirement: { type: 'streak', target: 3, metric: 'wins' },
    rarity: 'common',
  },
  {
    id: 'iron_will',
    name: 'Eiserner Wille',
    description: 'Gewinne ein Spiel nach 0:1 Rückstand (Best of 3)',
    category: 'consistency',
    tier: 'silver',
    icon: '💪',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'comeback_one_leg' },
    rarity: 'rare',
  },
  {
    id: 'domination',
    name: 'Dominanz',
    description: 'Gewinne 5 Spiele in Folge ohne Satzverlust',
    category: 'consistency',
    tier: 'platinum',
    icon: '👑',
    points: 200,
    requirement: { type: 'streak', target: 5, metric: 'whitewash_streak' },
    rarity: 'legendary',
  },
  {
    id: 'efficient_winner',
    name: 'Effizienter Sieger',
    description: 'Gewinne ein Spiel mit unter 15 Darts pro Leg (Durchschnitt)',
    category: 'consistency',
    tier: 'gold',
    icon: '⚡',
    points: 100,
    requirement: { type: 'special', target: 15, metric: 'avg_darts_per_leg_max' },
    rarity: 'epic',
  },
  {
    id: 'perfect_match',
    name: 'Perfektes Match',
    description: 'Gewinne ein Match ohne einzigen Bust',
    category: 'consistency',
    tier: 'platinum',
    icon: '💎',
    points: 150,
    requirement: { type: 'special', target: 1, metric: 'match_no_bust' },
    rarity: 'legendary',
  },
  {
    id: 'rally_master',
    name: 'Rally Meister',
    description: 'Spiele ein Leg mit mindestens 20 Würfen',
    category: 'consistency',
    tier: 'silver',
    icon: '🔄',
    points: 40,
    requirement: { type: 'special', target: 20, metric: 'leg_visits_min' },
    rarity: 'rare',
  },
  {
    id: 'nail_biter',
    name: 'Nervenkrimi',
    description: 'Gewinne ein Spiel mit einem Punkt Differenz',
    category: 'consistency',
    tier: 'gold',
    icon: '😰',
    points: 75,
    requirement: { type: 'special', target: 1, metric: 'close_win' },
    rarity: 'epic',
  },
  {
    id: 'marathon_man',
    name: 'Marathon Mann',
    description: 'Spiele ein Match über 30 Minuten',
    category: 'consistency',
    tier: 'silver',
    icon: '🏃',
    points: 50,
    requirement: { type: 'special', target: 1800, metric: 'game_time_min' },
    rarity: 'rare',
  },
  {
    id: 'late_bloomer',
    name: 'Spätzünder',
    description: 'Gewinne ein Leg nach 100+ Punkten Rückstand',
    category: 'consistency',
    tier: 'silver',
    icon: '🌸',
    points: 60,
    requirement: { type: 'special', target: 100, metric: 'leg_comeback_points' },
    rarity: 'rare',
  },
  {
    id: 'perfect_start',
    name: 'Perfekter Start',
    description: 'Gewinne das erste Leg in 10 Spielen hintereinander',
    category: 'consistency',
    tier: 'gold',
    icon: '🚀',
    points: 100,
    requirement: { type: 'streak', target: 10, metric: 'first_leg_wins' },
    rarity: 'epic',
  },
  {
    id: 'finisher',
    name: 'Finisher',
    description: 'Gewinne das letzte Leg in 10 Spielen hintereinander',
    category: 'consistency',
    tier: 'gold',
    icon: '🏁',
    points: 100,
    requirement: { type: 'streak', target: 10, metric: 'last_leg_wins' },
    rarity: 'epic',
  },
  {
    id: 'reverse_sweep',
    name: 'Reverse Sweep',
    description: 'Gewinne ein Best of 5 nach 0:2 Rückstand',
    category: 'consistency',
    tier: 'platinum',
    icon: '🔄',
    points: 200,
    requirement: { type: 'special', target: 1, metric: 'reverse_sweep' },
    rarity: 'legendary',
  },
  {
    id: 'no_mercy',
    name: 'Keine Gnade',
    description: 'Gewinne 3 Spiele hintereinander ohne Satzverlust',
    category: 'consistency',
    tier: 'gold',
    icon: '⚔️',
    points: 100,
    requirement: { type: 'streak', target: 3, metric: 'whitewash_streak' },
    rarity: 'epic',
  },

  // ===== ADDITIONAL TRAINING ACHIEVEMENTS (15) =====
  {
    id: 'training_enthusiast',
    name: 'Training Enthusiast',
    description: 'Absolviere 25 Trainingseinheiten',
    category: 'training',
    tier: 'bronze',
    icon: '🎯',
    points: 40,
    requirement: { type: 'count', target: 25, metric: 'training_completed' },
    rarity: 'common',
  },
  {
    id: 'training_legend',
    name: 'Training Legende',
    description: 'Absolviere 250 Trainingseinheiten',
    category: 'training',
    tier: 'platinum',
    icon: '🏆',
    points: 200,
    requirement: { type: 'count', target: 250, metric: 'training_completed' },
    rarity: 'legendary',
  },
  {
    id: 'doubles_master',
    name: 'Doubles Meister',
    description: 'Erreiche 80% in einem Doubles Training',
    category: 'training',
    tier: 'gold',
    icon: '🎯',
    points: 75,
    requirement: { type: 'special', target: 80, metric: 'training_doubles_percent' },
    rarity: 'epic',
  },
  {
    id: 'scoring_trainer',
    name: 'Scoring Trainer',
    description: 'Erreiche 100+ Average in 10 Scoring Trainings',
    category: 'training',
    tier: 'platinum',
    icon: '📈',
    points: 150,
    requirement: { type: 'count', target: 10, metric: 'training_scoring_100' },
    rarity: 'legendary',
  },
  {
    id: 'training_variety',
    name: 'Training Vielfalt',
    description: 'Absolviere jeden Trainingstyp mindestens 5 mal',
    category: 'training',
    tier: 'silver',
    icon: '🌈',
    points: 60,
    requirement: { type: 'special', target: 5, metric: 'all_training_types' },
    rarity: 'rare',
  },
  {
    id: 'late_night_training',
    name: 'Nachttraining',
    description: 'Absolviere ein Training nach 22 Uhr',
    category: 'training',
    tier: 'bronze',
    icon: '🌙',
    points: 20,
    requirement: { type: 'special', target: 1, metric: 'training_late' },
    rarity: 'common',
  },
  {
    id: 'morning_routine',
    name: 'Morgenroutine',
    description: 'Absolviere 10 Trainings vor 10 Uhr',
    category: 'training',
    tier: 'silver',
    icon: '☀️',
    points: 50,
    requirement: { type: 'count', target: 10, metric: 'training_morning' },
    rarity: 'rare',
  },
  {
    id: 'training_marathon',
    name: 'Training Marathon',
    description: 'Absolviere 5 Trainings an einem Tag',
    category: 'training',
    tier: 'gold',
    icon: '🏃',
    points: 100,
    requirement: { type: 'special', target: 5, metric: 'training_one_day' },
    rarity: 'epic',
  },
  {
    id: 'checkout_training',
    name: 'Checkout Training Profi',
    description: 'Erreiche 90% in einem Checkout Training',
    category: 'training',
    tier: 'platinum',
    icon: '🎯',
    points: 150,
    requirement: { type: 'special', target: 90, metric: 'training_checkout_percent' },
    rarity: 'legendary',
  },
  {
    id: 'around_the_board',
    name: 'Rund ums Board',
    description: 'Absolviere 50 Around the Clock Trainings',
    category: 'training',
    tier: 'gold',
    icon: '🔄',
    points: 100,
    requirement: { type: 'count', target: 50, metric: 'training_around_clock' },
    rarity: 'epic',
  },
  {
    id: 'training_streak',
    name: 'Training Serie',
    description: 'Trainiere 14 Tage in Folge',
    category: 'training',
    tier: 'platinum',
    icon: '🔥',
    points: 200,
    requirement: { type: 'streak', target: 14, metric: 'daily_training' },
    rarity: 'legendary',
  },
  {
    id: 'weekend_training',
    name: 'Wochenend Training',
    description: 'Absolviere 25 Trainings am Wochenende',
    category: 'training',
    tier: 'silver',
    icon: '📅',
    points: 50,
    requirement: { type: 'count', target: 25, metric: 'weekend_training' },
    rarity: 'rare',
  },
  {
    id: 'quick_learner',
    name: 'Schnelllerner',
    description: 'Verbessere dein Training-Ergebnis um 50% in einem Modus',
    category: 'training',
    tier: 'gold',
    icon: '📚',
    points: 75,
    requirement: { type: 'special', target: 50, metric: 'training_improvement' },
    rarity: 'epic',
  },
  {
    id: 'triple_training',
    name: 'Triple Training',
    description: 'Treffe 100 Triples in einem Training',
    category: 'training',
    tier: 'gold',
    icon: '🎯',
    points: 100,
    requirement: { type: 'special', target: 100, metric: 'training_triples' },
    rarity: 'epic',
  },
  {
    id: 'training_consistency',
    name: 'Training Konsistenz',
    description: 'Erreiche 3 mal hintereinander 80%+ im gleichen Training',
    category: 'training',
    tier: 'platinum',
    icon: '⭐',
    points: 150,
    requirement: { type: 'streak', target: 3, metric: 'training_80_percent' },
    rarity: 'legendary',
  },

  // ===== ADDITIONAL SPECIAL ACHIEVEMENTS (15) =====
  {
    id: 'fifteen_darter',
    name: '15-Darter',
    description: 'Beende ein Leg mit nur 15 Darts (501)',
    category: 'special',
    tier: 'gold',
    icon: '⭐',
    points: 150,
    requirement: { type: 'special', target: 15, metric: 'leg_darts' },
    rarity: 'epic',
    hidden: true,
  },
  {
    id: 'eighteen_darter',
    name: '18-Darter',
    description: 'Beende ein Leg mit nur 18 Darts (501)',
    category: 'special',
    tier: 'silver',
    icon: '🌟',
    points: 75,
    requirement: { type: 'special', target: 18, metric: 'leg_darts' },
    rarity: 'rare',
  },
  {
    id: 'quick_301',
    name: 'Schnelle 301',
    description: 'Beende ein 301 Leg in unter 9 Darts',
    category: 'special',
    tier: 'gold',
    icon: '⚡',
    points: 100,
    requirement: { type: 'special', target: 9, metric: 'leg_301_darts' },
    rarity: 'epic',
    hidden: true,
  },
  {
    id: 'perfect_301',
    name: 'Perfekte 301',
    description: 'Beende ein 301 Leg mit 6 Darts',
    category: 'special',
    tier: 'diamond',
    icon: '💎',
    points: 400,
    requirement: { type: 'special', target: 6, metric: 'leg_301_darts' },
    rarity: 'legendary',
    hidden: true,
  },
  {
    id: 'double_180',
    name: 'Doppel 180',
    description: 'Erziele 2x 180 in einem Spiel',
    category: 'special',
    tier: 'gold',
    icon: '🔥',
    points: 100,
    requirement: { type: 'special', target: 2, metric: 'match_180_count' },
    rarity: 'epic',
  },
  {
    id: 'ton_80_streak',
    name: '180 Serie',
    description: 'Erziele 180 in 3 Spielen hintereinander',
    category: 'special',
    tier: 'platinum',
    icon: '🎯',
    points: 150,
    requirement: { type: 'streak', target: 3, metric: 'game_180' },
    rarity: 'legendary',
  },
  {
    id: 'all_180s',
    name: '180 Sammler',
    description: 'Erziele 100x einen 180',
    category: 'special',
    tier: 'diamond',
    icon: '💫',
    points: 300,
    requirement: { type: 'count', target: 100, metric: 'score_180' },
    rarity: 'legendary',
  },
  {
    id: 'lucky_number',
    name: 'Glückszahl',
    description: 'Gewinne ein Spiel an deinem Geburtstag',
    category: 'special',
    tier: 'bronze',
    icon: '🎂',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'birthday_win' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'new_year_player',
    name: 'Neujahrs Spieler',
    description: 'Spiele am 1. Januar',
    category: 'special',
    tier: 'bronze',
    icon: '🎊',
    points: 25,
    requirement: { type: 'special', target: 1, metric: 'new_year_game' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'christmas_special',
    name: 'Weihnachts-Special',
    description: 'Spiele an Weihnachten (24.-26. Dezember)',
    category: 'special',
    tier: 'bronze',
    icon: '🎄',
    points: 30,
    requirement: { type: 'special', target: 1, metric: 'christmas_game' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'midnight_winner',
    name: 'Mitternachts Sieger',
    description: 'Gewinne ein Spiel zwischen 00:00 und 01:00',
    category: 'special',
    tier: 'silver',
    icon: '🌃',
    points: 50,
    requirement: { type: 'special', target: 1, metric: 'midnight_win' },
    rarity: 'rare',
  },
  {
    id: 'shutout',
    name: 'Shutout',
    description: 'Gewinne ein Leg bevor Gegner checken kann (301)',
    category: 'special',
    tier: 'gold',
    icon: '🚫',
    points: 100,
    requirement: { type: 'special', target: 1, metric: 'shutout_leg' },
    rarity: 'epic',
  },
  {
    id: 'robbery',
    name: 'Raub',
    description: 'Gewinne ein Leg mit dem ersten Checkout-Versuch',
    category: 'special',
    tier: 'silver',
    icon: '💰',
    points: 60,
    requirement: { type: 'special', target: 1, metric: 'first_dart_checkout' },
    rarity: 'rare',
  },
  {
    id: 'mirror_match',
    name: 'Spiegelmatch',
    description: 'Beende ein Leg mit exakt gleichem Score wie der Gegner',
    category: 'special',
    tier: 'bronze',
    icon: '🪞',
    points: 30,
    requirement: { type: 'special', target: 1, metric: 'mirror_score' },
    rarity: 'common',
    hidden: true,
  },
  {
    id: 'speed_round',
    name: 'Speedrunde',
    description: 'Beende ein Spiel in unter 3 Minuten',
    category: 'special',
    tier: 'platinum',
    icon: '💨',
    points: 150,
    requirement: { type: 'special', target: 180, metric: 'game_time_max' },
    rarity: 'legendary',
  },

  // ===== ADDITIONAL MASTER ACHIEVEMENTS (10) =====
  {
    id: 'rising_star',
    name: 'Aufsteigender Stern',
    description: 'Erreiche 2.500 Achievement-Punkte',
    category: 'master',
    tier: 'silver',
    icon: '⭐',
    points: 100,
    requirement: { type: 'value', target: 2500, metric: 'achievement_points' },
    rarity: 'rare',
  },
  {
    id: 'seasoned_pro',
    name: 'Erfahrener Profi',
    description: 'Erreiche 5.000 Achievement-Punkte',
    category: 'master',
    tier: 'gold',
    icon: '🏅',
    points: 200,
    requirement: { type: 'value', target: 5000, metric: 'achievement_points' },
    rarity: 'epic',
  },
  {
    id: 'elite_player',
    name: 'Elite Spieler',
    description: 'Erreiche 7.500 Achievement-Punkte',
    category: 'master',
    tier: 'platinum',
    icon: '💎',
    points: 300,
    requirement: { type: 'value', target: 7500, metric: 'achievement_points' },
    rarity: 'legendary',
  },
  {
    id: 'completionist',
    name: 'Vollender',
    description: 'Schalte 50 Achievements frei',
    category: 'master',
    tier: 'gold',
    icon: '🏆',
    points: 150,
    requirement: { type: 'count', target: 50, metric: 'achievements_unlocked' },
    rarity: 'epic',
  },
  {
    id: 'achievement_hunter',
    name: 'Achievement Jäger',
    description: 'Schalte 100 Achievements frei',
    category: 'master',
    tier: 'platinum',
    icon: '🎯',
    points: 300,
    requirement: { type: 'count', target: 100, metric: 'achievements_unlocked' },
    rarity: 'legendary',
  },
  {
    id: 'perfectionist',
    name: 'Perfektionist',
    description: 'Schalte alle Achievements frei',
    category: 'master',
    tier: 'diamond',
    icon: '💯',
    points: 1000,
    requirement: { type: 'special', target: 145, metric: 'achievements_unlocked' },
    rarity: 'legendary',
  },
  {
    id: 'triple_threat',
    name: 'Triple Bedrohung',
    description: 'Gewinne je 50 Spiele in 301, 501 und 701',
    category: 'master',
    tier: 'diamond',
    icon: '👑',
    points: 400,
    requirement: { type: 'special', target: 50, metric: 'wins_all_modes' },
    rarity: 'legendary',
  },
  {
    id: 'jack_of_all_trades',
    name: 'Tausendsassa',
    description: 'Erreiche Gold-Tier in jeder Kategorie',
    category: 'master',
    tier: 'platinum',
    icon: '🌟',
    points: 250,
    requirement: { type: 'special', target: 7, metric: 'gold_all_categories' },
    rarity: 'legendary',
  },
  {
    id: 'dedication',
    name: 'Hingabe',
    description: 'Spiele an 100 verschiedenen Tagen',
    category: 'master',
    tier: 'platinum',
    icon: '📅',
    points: 200,
    requirement: { type: 'count', target: 100, metric: 'unique_play_days' },
    rarity: 'legendary',
  },
  {
    id: 'ultimate_master',
    name: 'Ultimativer Meister',
    description: 'Erreiche 20.000 Achievement-Punkte',
    category: 'master',
    tier: 'diamond',
    icon: '👑',
    points: 1000,
    requirement: { type: 'value', target: 20000, metric: 'achievement_points' },
    rarity: 'legendary',
  },
];

// Helper functions
export const getAchievementById = (id: string): Achievement | undefined => {
  return ACHIEVEMENTS.find(a => a.id === id);
};

export const getAchievementsByCategory = (category: AchievementCategory): Achievement[] => {
  return ACHIEVEMENTS.filter(a => a.category === category);
};

export const getAchievementsByTier = (tier: AchievementTier): Achievement[] => {
  return ACHIEVEMENTS.filter(a => a.tier === tier);
};

export const getTotalPoints = (achievements: Achievement[]): number => {
  return achievements.reduce((sum, a) => sum + a.points, 0);
};

export const getCategoryName = (category: AchievementCategory): string => {
  const names: Record<AchievementCategory, string> = {
    first_steps: 'Erste Schritte',
    scoring: 'Scoring',
    checkout: 'Checkout',
    training: 'Training',
    consistency: 'Beständigkeit',
    special: 'Spezial',
    master: 'Meisterschaft',
  };
  return names[category];
};

export const getTierColor = (tier: AchievementTier): string => {
  const colors: Record<AchievementTier, string> = {
    bronze: '#CD7F32',
    silver: '#C0C0C0',
    gold: '#FFD700',
    platinum: '#E5E4E2',
    diamond: '#B9F2FF',
  };
  return colors[tier];
};

export const getRarityColor = (rarity: 'common' | 'rare' | 'epic' | 'legendary'): string => {
  const colors = {
    common: '#9CA3AF',    // gray
    rare: '#3B82F6',      // blue
    epic: '#A855F7',      // purple
    legendary: '#F59E0B', // amber
  };
  return colors[rarity];
};
