import { ICON_PATHS, type IconName } from './paths';

/**
 * Emoji -> custom icon.
 *
 * The app used ~250 distinct emoji across its interface, its 463 achievements
 * and its avatar palette. Drawing 250 bespoke glyphs would have produced 250
 * mediocre ones; instead the set covers the semantic space and this table maps
 * every emoji that appeared onto the closest member of it.
 *
 * ⚠️ `iconForEmoji` NEVER returns undefined for a non-empty string — an unmapped
 * emoji resolves through a small set of Unicode-block heuristics and finally to
 * `target`, the app's own mark. That guarantee is what lets call sites drop the
 * emoji entirely rather than keeping it as a fallback, which would have put the
 * platform glyph back on screen for anything the table missed.
 */
export const EMOJI_TO_ICON: Record<string, IconName> = {
  '🚫': 'ban',
  '🙅': 'ban',
  '🛑': 'ban',
  '📵': 'ban',
  '🚭': 'ban',
  '⏹': 'ban',
  '🕳': 'ban',
  '🎱': 'board',
  '🎳': 'board',
  '🀄': 'board',
  '🧩': 'board',
  '⚡': 'bolt',
  '💥': 'bolt',
  '🌩': 'bolt',
  '⛈': 'bolt',
  '🌪': 'bolt',
  '🌀': 'bolt',
  '💢': 'bolt',
  '🏃': 'bolt',
  '🤸': 'bolt',
  '📜': 'book',
  '📃': 'book',
  '📄': 'book',
  '📋': 'book',
  '📝': 'book',
  '🗒': 'book',
  '🦉': 'brain',
  '🎓': 'brain',
  '📚': 'brain',
  '📖': 'brain',
  '🧘': 'brain',
  '🧘‍♂': 'brain',
  '🧹': 'broom',
  '🧼': 'broom',
  '🫧': 'broom',
  '🪣': 'broom',
  '🗑': 'broom',
  '🚽': 'broom',
  '🐛': 'bug',
  '🐞': 'bug',
  '🦠': 'bug',
  '🕷': 'bug',
  '💡': 'bulb',
  '🧠': 'bulb',
  '💯': 'bullseye',
  '🔟': 'bullseye',
  '✌': 'bullseye',
  '☝': 'bullseye',
  '🖐': 'bullseye',
  '🤏': 'bullseye',
  '📅': 'calendar',
  '📆': 'calendar',
  '🗓': 'calendar',
  '📊': 'chartBar',
  '🧮': 'chartBar',
  '🔢': 'chartBar',
  '📉': 'chartDown',
  '⬇': 'chartDown',
  '↘': 'chartDown',
  '🐌': 'chartDown',
  '🐢': 'chartDown',
  '〽': 'chartLine',
  '📐': 'chartLine',
  '📏': 'chartLine',
  '📈': 'chartUp',
  '⬆': 'chartUp',
  '↗': 'chartUp',
  '🚀': 'chartUp',
  '✓': 'check',
  '✔': 'check',
  '☑': 'check',
  '✅': 'checkCircle',
  '🟢': 'checkCircle',
  '🆗': 'checkCircle',
  '🗂': 'clipboard',
  '📁': 'clipboard',
  '📂': 'clipboard',
  '🗃': 'clipboard',
  '🕐': 'clock',
  '🕛': 'clock',
  '⏰': 'clock',
  '⏱': 'clock',
  '⏲': 'clock',
  '⌛': 'clock',
  '⏳': 'clock',
  '⌚': 'clock',
  '✗': 'close',
  '✘': 'close',
  '❎': 'close',
  '❌': 'closeCircle',
  '⛔': 'closeCircle',
  '👑': 'crown',
  '🫅': 'crown',
  '🤴': 'crown',
  '👸': 'crown',
  '🎩': 'crown',
  '🪃': 'dart',
  '🗡': 'dart',
  '⚔': 'dart',
  '🔱': 'dart',
  '🏒': 'dart',
  '🏑': 'dart',
  '🥍': 'dart',
  '🏏': 'dart',
  '🎲': 'dice',
  '🎰': 'dice',
  '🃏': 'dice',
  '♟': 'dice',
  '🎮': 'dice',
  '🔭': 'eye',
  '🪞': 'eye',
  '🫣': 'eye',
  '🏁': 'flag',
  '🚩': 'flag',
  '🏳': 'flag',
  '🎌': 'flag',
  '🏴': 'flag',
  '🐦‍⬛': 'flag',
  '📛': 'flag',
  '🔥': 'flame',
  '🌋': 'flame',
  '🧨': 'flame',
  '💣': 'flame',
  '🥵': 'flame',
  '♨': 'flame',
  '😤': 'flame',
  '🥊': 'flame',
  '⚙': 'gear',
  '🔧': 'gear',
  '🔨': 'gear',
  '🛠': 'gear',
  '⚗': 'gear',
  '🔬': 'gear',
  '💎': 'gem',
  '🔷': 'gem',
  '🔶': 'gem',
  '🔸': 'gem',
  '🔹': 'gem',
  '💿': 'gem',
  '💰': 'gem',
  '🔮': 'gem',
  '🫥': 'ghost',
  '🫠': 'ghost',
  '😵': 'ghost',
  '😵‍💫': 'ghost',
  '🤯': 'ghost',
  '😰': 'ghost',
  '😬': 'ghost',
  '😱': 'ghost',
  '😩': 'ghost',
  '😫': 'ghost',
  '😨': 'ghost',
  '💩': 'ghost',
  '🎁': 'gift',
  '🎄': 'gift',
  '🎃': 'gift',
  '🧸': 'gift',
  '🍔': 'gift',
  '🍽': 'gift',
  '🎂': 'gift',
  '🌍': 'globe',
  '🌎': 'globe',
  '🌏': 'globe',
  '🌐': 'globe',
  '✈': 'globe',
  '🪂': 'globe',
  '#⃣': 'hash',
  '🔣': 'hash',
  '🔠': 'hash',
  '🔡': 'hash',
  '🔤': 'hash',
  '❤': 'heart',
  '🧡': 'heart',
  '💛': 'heart',
  '💚': 'heart',
  '💙': 'heart',
  '💜': 'heart',
  '🖤': 'heart',
  '🤍': 'heart',
  '🤎': 'heart',
  '💗': 'heart',
  '💖': 'heart',
  '💘': 'heart',
  '💝': 'heart',
  '💓': 'heart',
  '💕': 'heart',
  '💞': 'heart',
  '💟': 'heart',
  '❣': 'heart',
  '💔': 'heart',
  '😞': 'heart',
  '😔': 'heart',
  '😢': 'heart',
  '😭': 'heart',
  '🏠': 'home',
  '🏡': 'home',
  '🏚': 'home',
  '🏘': 'home',
  'ℹ': 'info',
  '💬': 'info',
  '🗨': 'info',
  '📣': 'info',
  '📢': 'info',
  '🔑': 'key',
  '🗝': 'key',
  '🔒': 'lock',
  '🔐': 'lock',
  '🔏': 'lock',
  '🛡': 'lock',
  '📧': 'mail',
  '✉': 'mail',
  '📨': 'mail',
  '📩': 'mail',
  '📬': 'mail',
  '📮': 'mail',
  '🏅': 'medal',
  '🎖': 'medal',
  '🥈': 'medal',
  '🥉': 'medal',
  '🎗': 'medal',
  '🌙': 'moon',
  '🌑': 'moon',
  '🌚': 'moon',
  '🌃': 'moon',
  '🌌': 'moon',
  '🛏': 'moon',
  '😴': 'moon',
  '💤': 'moon',
  '🎵': 'music',
  '🎶': 'music',
  '🎸': 'music',
  '🎹': 'music',
  '🎺': 'music',
  '🎻': 'music',
  '🥁': 'music',
  '🎷': 'music',
  '🎤': 'music',
  '🎧': 'music',
  '🎼': 'music',
  '🪕': 'music',
  '🔇': 'mute',
  '🤫': 'mute',
  '🙊': 'mute',
  '🙈': 'mute',
  '🙉': 'mute',
  '🎉': 'party',
  '🥳': 'party',
  '🍻': 'party',
  '🍺': 'party',
  '🎆': 'party',
  '🎈': 'party',
  '🎭': 'party',
  '🎬': 'party',
  '％': 'percent',
  '﹪': 'percent',
  '📱': 'phone',
  '📲': 'phone',
  '💻': 'phone',
  '🖥': 'phone',
  '➕': 'plus',
  '✚': 'plus',
  '❓': 'question',
  '❔': 'question',
  '🤔': 'question',
  '🧐': 'question',
  '🔄': 'refresh',
  '🔁': 'refresh',
  '🔂': 'refresh',
  '♻': 'refresh',
  '🔙': 'refresh',
  '↩': 'refresh',
  '⤴': 'refresh',
  '♾': 'refresh',
  '🏵': 'ribbon',
  '🎀': 'ribbon',
  '🤖': 'robot',
  '🦾': 'robot',
  '👾': 'robot',
  '🛸': 'robot',
  '🛫': 'rocket',
  '🛰': 'rocket',
  '⚖': 'scale',
  '🏋': 'scale',
  '🏋‍♂': 'scale',
  '🔍': 'search',
  '🔎': 'search',
  '👀': 'search',
  '👁': 'search',
  '🦺': 'shield',
  '⛑': 'shield',
  '🥋': 'shield',
  '💀': 'skull',
  '☠': 'skull',
  '🪦': 'skull',
  '😈': 'skull',
  '👹': 'skull',
  '👺': 'skull',
  '🎡': 'slot',
  '🎢': 'slot',
  '🎠': 'slot',
  '❄': 'snow',
  '🧊': 'snow',
  '🥶': 'snow',
  '☃': 'snow',
  '⛄': 'snow',
  '🌧': 'snow',
  '⛸': 'snow',
  '🎿': 'snow',
  '🛷': 'snow',
  '🏂': 'snow',
  '🔊': 'sound',
  '🔉': 'sound',
  '🔈': 'sound',
  '✨': 'sparkle',
  '💫': 'sparkle',
  '🪄': 'sparkle',
  '🎊': 'sparkle',
  '🪅': 'sparkle',
  '🎨': 'sparkle',
  '🦄': 'sparkle',
  '🌈': 'sparkle',
  '🌱': 'sprout',
  '🌿': 'sprout',
  '🌳': 'sprout',
  '🌲': 'sprout',
  '🍃': 'sprout',
  '🔰': 'sprout',
  '⭐': 'star',
  '🌟': 'star',
  '🌠': 'star',
  '✳': 'star',
  '❇': 'star',
  '🌸': 'star',
  '🍀': 'star',
  '☘': 'star',
  '🌺': 'star',
  '☀': 'sun',
  '🌞': 'sun',
  '🌅': 'sun',
  '🌤': 'sun',
  '🔆': 'sun',
  '🔅': 'sun',
  '🎯': 'target',
  '◎': 'target',
  '🔴': 'target',
  '⭕': 'target',
  '🎪': 'target',
  '📍': 'target',
  '📌': 'target',
  '🔝': 'target',
  '🏹': 'target',
  '⛳': 'target',
  '⚽': 'target',
  '🏀': 'target',
  '🏈': 'target',
  '⚾': 'target',
  '🎾': 'target',
  '🏐': 'target',
  '🏉': 'target',
  '🥏': 'target',
  '🏓': 'target',
  '🏸': 'target',
  '🥅': 'target',
  '🏆': 'trophy',
  '🥇': 'trophy',
  '🏟': 'trophy',
  '🏛': 'trophy',
  '🏯': 'trophy',
  '🏦': 'trophy',
  '📤': 'upload',
  '📥': 'upload',
  '💾': 'upload',
  '👤': 'user',
  '🧑': 'user',
  '👨': 'user',
  '👩': 'user',
  '👦': 'user',
  '👧': 'user',
  '👶': 'user',
  '🧒': 'user',
  '👴': 'user',
  '👵': 'user',
  '🧓': 'user',
  '🙂': 'user',
  '😀': 'user',
  '😃': 'user',
  '😄': 'user',
  '😁': 'user',
  '😊': 'user',
  '🙃': 'user',
  '😏': 'user',
  '🥷': 'user',
  '🧙': 'user',
  '🦸': 'user',
  '🤡': 'user',
  '👻': 'user',
  '🥸': 'user',
  '🤠': 'user',
  '🤦': 'user',
  '🆔': 'user',
  '👥': 'users',
  '👪': 'users',
  '👫': 'users',
  '👬': 'users',
  '👭': 'users',
  '🤝': 'users',
  '🧑‍🤝‍🧑': 'users',
  '⚠': 'warning',
  '🚨': 'warning',
  '🚦': 'warning',
  '🟠': 'warning',
  '🟡': 'warning',
  '‼': 'warning',
  '⁉': 'warning',
  '👋': 'wave',
  '🙌': 'wave',
  '👏': 'wave',
  '🤙': 'wave',
  '🖖': 'wave',
  '👌': 'wave',
  '👍': 'wave',
  '💪': 'wave',
  '😅': 'wave',
  '🐟': 'wave',
  '🌊': 'wave',
  '🌬': 'wave',
  '💨': 'wave',
};

/** Strips variation selectors and skin-tone modifiers before lookup. */
function normalise(emoji: string): string {
  return emoji
    .replace(/[\uFE0E\uFE0F]/g, '')
    .replace(/[\u{1F3FB}-\u{1F3FF}]/gu, '')
    .trim();
}

const FALLBACK: IconName = 'target';

export function iconForEmoji(emoji: string | null | undefined): IconName {
  if (!emoji) return FALLBACK;
  // Already an icon name — data files are migrating from emoji to names, and
  // this pass-through lets both forms coexist during (and after) that move.
  if (emoji in ICON_PATHS) return emoji as IconName;
  const key = normalise(emoji);
  if (!key) return FALLBACK;
  const direct = EMOJI_TO_ICON[key];
  if (direct) return direct;

  // A ZWJ sequence ("person + zwj + role") keeps its meaning in the first glyph.
  const first = normalise([...key][0] ?? '');
  if (first && EMOJI_TO_ICON[first]) return EMOJI_TO_ICON[first];

  // Block heuristics for anything the table never saw — the avatar palette is
  // ~1900 glyphs and the table deliberately does not enumerate it.
  const cp = key.codePointAt(0) ?? 0;
  if (cp >= 0x1f1e6 && cp <= 0x1f1ff) return 'flag';   // regional indicators
  if (cp >= 0x1f600 && cp <= 0x1f64f) return 'user';   // faces & gestures
  if (cp >= 0x1f400 && cp <= 0x1f4ff) return 'sprout'; // animals & nature
  if (cp >= 0x1f34a && cp <= 0x1f37f) return 'gift';   // food & drink
  if (cp >= 0x1f680 && cp <= 0x1f6ff) return 'rocket'; // transport
  return FALLBACK;
}
